{% set name = "xcfun" %}
{% set version = "2.1.1" %}
{% set sha256 = "8b602df74c7be83d501532565deafd1b7881946d94789122f24c309a669298ab" %}
{% set build = 9 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftlibs/xcfun/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('xcfun', max_pin='x.x') }}

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11  # [build_platform != target_platform]  
    - cmake >=3.14
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - python
    - pybind11
    - pybind11-abi
  run:
    - numpy
    - python  # [win]

test:
  requires:
    - numpy
    - pytest
    - pip
  imports:
    - xcfun
  commands:
    - pip check
    # Verify library
    - if not exist %PREFIX%\\Library\\bin\\xcfun.dll exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\xcfun.lib exit 1                 # [win]
    - if not exist %PREFIX%\\Lib\\site-packages\\xcfun\\_xcfun*.pyd exit 1  # [win]
    # Inspect linkage
    - ldd -v $PREFIX/lib/libxcfun$SHLIB_EXT                                 # [linux]
    - otool -L $PREFIX/lib/libxcfun$SHLIB_EXT                               # [osx]
    - export PYLIB_EXT=`$PYTHON -c 'import sysconfig; print(sysconfig.get_config_var("EXT_SUFFIX"))'`  # [unix]
    - ldd -v $SP_DIR/xcfun/_xcfun$PYLIB_EXT  # [linux]
    - otool -L $SP_DIR/xcfun/_xcfun$PYLIB_EXT  # [osx]
    # Actually test
    - python -m pytest --pyargs xcfun

outputs:
  - name: xcfun
    files:
      - include/XCFun              # [not win]
      - lib/libxcfun*              # [not win]
      - share/cmake/XCFun          # [not win]
      - {{ SP_DIR }}/xcfun         # [not win]
      - Library\include\XCFun      # [win]
      - Library\bin\xcfun*         # [win]
      - Library\lib\xcfun*         # [win]
      - Library\share\cmake\XCFun  # [win]
      - Lib\site-packages\xcfun    # [win]

about:
  home: https://github.com/dftlibs/xcfun
  dev_url: https://github.com/dftlibs/xcfun
  doc_url: https://xcfun.readthedocs.io
  doc_source_url: https://github.com/dftlibs/xcfun/blob/master/doc/index.rst
  license: MPL-2.0
  license_url: https://opensource.org/licenses/MPL-2.0
  license_file: LICENSE.md
  license_family: MOZILLA
  summary: "Exchange-Correlation functionals with arbitrary order derivatives."

extra:
  recipe-maintainers:
    - robertodr
    - bast
